flowchart TD
    %% 基本节点类型
    A[Rectangle Node]
    B(Rounded Rectangle Node)
    C{Diamond Node}
    D((Circle Node))
    
    %% 复杂节点类型
    E([Stadium Node])
    F[[Subroutine Node]]
    G[(Cylindrical Database Node)]
    H{{Hexagon Node}}
    I[/Parallelogram Node/]
    J[/Trapezoid Node\]
    K(((Double Circle Node)))
    L>Label Node>
    
    %% 特殊节点类型
    Image1["📷 Image Node"]
    Text1["📝 Text Content Node"]
    Button1(((🔘 Button Node)))
    
    %% 带引号的节点
    M["Rectangle with quotes"]
    N("Rounded with quotes")
    
    %% 连接关系
    A --> B
    B --> C
    C --> D
    D --> E
    E --> F
    F --> G
    G --> H
    H --> I
    I --> J
    J --> K
    K --> L
    L --> Image1
    Image1 --> Text1
    Text1 --> Button1
    Button1 --> M
    M --> N
    
    %% 注释示例
    A
    %% This is a comment for Rectangle Node
    
    E
    %% This is a comment for Stadium Node
    
    Image1
    %% This is a comment for Image Node
